### ISSUE TITLE
Error en selección obligatoria de Alternativas a un plan 

### ISSUE THREAD

**Issue by gustavoigl** [Bowerystudio/swapmymood-api#22]
@facularrauri 

Mirando el site map vi que en nn la pantalla de alternativas no debería ser obligatorio la seleccion y nosotros lo estamos haciendo.

Porfa quitar esto. Decime porfa si hay que actualizar del lado de Ale algo.
Abrazo!
Mil gracias

![Screen Shot 2020-05-19 at 12 21 29 PM](https://user-images.githubusercontent.com/41792809/82558228-9699d700-9b43-11ea-8b38-df94135861df.png)

**Comment by facularrauri** [comment]
Un swap puede no tener asociado ninguna alternativa?
